#eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjIyMjcyNjV9.NxedWb-KQO9hk22-NMUvPE2i1MScyQFAROmsXDi1CKo
### GENE INDEX
GET http://localhost:3000/genes

### GENE SHOW

GET http://localhost:3000/genes/1.json

### GENE CREATE
POST http://localhost:3000/genes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjIyMjcyNjV9.NxedWb-KQO9hk22-NMUvPE2i1MScyQFAROmsXDi1CKo
Content-Type: application/json

{
  "common_name": "TP53"
}
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Dan",
  "email": "dan@dan.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dan@dan.com",
  "password": "password"
}