#eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI0NDIzNzR9.zcEo32rGBvdV_99Kf2K3j7iUQmwB0FrQoWG_EnsLtAw
### GENE INDEX
GET http://localhost:3000/genes.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI0NDMwMDZ9.lrEEE8d6mB8gn7Ko30HkAGBHGOiq3PbL7A5LSfXFqnM
### GENE SHOW

GET http://localhost:3000/genes/3.json

### GENE CREATE
POST http://localhost:3000/genes.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI0MjAzMzd9.T5lxCeHJ0wOkKKK3-VrfCP1nlyZyUFGoFS3L0xpyMOI
Content-Type: application/json

{
  "common_name": "EGFR"
}
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Dan",
  "email": "dan@dan.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dan@dan.com",
  "password": "password"
}